en:
  point_one:
    nouns:
      - dog
      - cat
      - imaginary girlfriend
      - penis
      - bitch boss
    verbs:
      - dying
      - on fire
      - annoying me
      - demanding sex
      - throwing up
