en:
  point_one:
    nouns:
      - dog
      - cat
      - goldfish
      - mentally deficient hamster
      - bearded grandma
      - Grindr date
      - imaginary girlfriend
      - pocket anaconda
      - bitch boss
      - own voulptous beard
      - personal moon buggy
      - pubic hair stylist
      - life-sized Hulk Hogan statue
      - ballistic missile shield
    verbs:
      - is dying
      - is on fire
      - is molesting me
      - is trying to kill me
      - is trying to eat me
      - is annoying me
      - is demanding sex
      - is throwing up
      - is on water
      - is parked in the handicapped spot
      - is trying to take me to Suplex City
      - is being held at gunpoint by Kim Jong Un
      - has spontaneously combusted
