en:
  point_one:
    nouns:
      - dog
      - cat
      - goldfish
      - mentally deficient hamster
      - bearded grandma
      - Grindr date
      - imaginary girlfriend
      - penis
      - bitch boss
    verbs:
      - dying
      - on fire
      - molesting me
      - trying to kill me
      - trying to eat me
      - annoying me
      - demanding sex
      - throwing up
